apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: nginx-pod
      labels: 
        env: dev   
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80



