apiVersion: v1
kind: Pod
metadata:
  name: photo-upload-pod
spec:
  volumes:
  - name: nipun-volume
    persistentVolumeClaim:
      claimName: my-pvc
  containers:
  - name: photo-container
    image: prabha060/photos-app:v1
    ports:
      - containerPort: 8501
    volumeMounts:
    - name: nipun-volume
      mountPath: /app/photos
      
