apiVersion: v1
kind: PersistentVolume
metadata: 
  name: my-pv
  labels:
    type: locals  # 🔥 label for Binding
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ""  # 🔥 disable dynamic binding
  hostPath:
    path: /data 
    type: DirectoryOrCreate
