apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  # 🔥 MUST (warna dynamic PV banega)
  selector:
    matchLabels:
      type: locals     # 🔥 ensure correct PV bind
