# Base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy app code
COPY main.py /app/

# Create photos folder
RUN mkdir /app/photos

# Install dependencies
RUN pip install --no-cache-dir streamlit pillow

# Expose Streamlit default port
EXPOSE 8501

# Run the app
CMD ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]
