FROM python:3.12-slim

WORKDIR /app

COPY app.py /app/

RUN mkdir -p /app/photos

RUN apt-get update && apt-get install -y \
    libgl1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir streamlit pillow

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0"]