apiVersion: v1
kind: Pod
metadata:
  name: dual-image-pod
spec:  
  containers:
    - name: nginx-container
      image: nginx
      ports:
      - containerPort: 80

    - name: firefox-container
      image: linuxserver/firefox  
      ports:
      - containerPort: 3000