apiVersion: v1
kind: Pod
metadata:
  name: dual-pod
spec:
  containers:
    - name: nginx-01
      image: nginx
      ports:
      - containerPort: 80

    - name: nginx-02
      image: nginx:alpine
      ports:
      - containerPort: 81  

