apiVersion: v1
kind: Pod
metadata:
  name: photo-upload-pod
spec:
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: my-pvc
  containers:
  - name: photo-container
    image: prabha060/photos-app:v1
    ports: 
      - containerPort: 8501
    volumeMounts:
    - mountPath: /app/photos
      name: shared-volume
