apiVersion: v1
kind: Pod
metadata: 
  name: photo-upload-pod
  labels:
    env: dev
    owner: prabha
spec:
  containers:
  - name: sample-container
    image: prabha060/photos-app:v1
    ports:
    - containerPort: 8501
