apiVersion: v1
kind: Pod
metadata:
  name: photo-pod
  labels:
    env: dev
    owner: prabha
spec:
  volumes:
  - name: nipun-volume
    emptyDir:
      sizeLimit: 1Gi
  containers:
  - name: test-container
    image: prabha060/photos-app:v1
    ports:
    - containerPort: 8501
    volumeMounts:
    - mountPath: /app/photos
      name: nipun-volume
  


