apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: my-pvc
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /home
      name: shared-volume
