apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  storageClassName: my-storage
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  capacity: 
    storage: 2Gi
  azureFile:
    secretName:  my-secret   
    shareName:  phabha-share
    readOnly: false


